[package]
name = "common"
edition = "2021"
version.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
hex.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
