[package]
name = "sakura-data"
edition = "2021"
version.workspace = true

[dependencies]
varint-rs.workspace = true
byteorder.workspace = true
paste.workspace = true

sakura-data-derive = { path = "sakura-data-derive" }
