[package]
name = "mavuika-environment"
edition = "2021"
version.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
tracing.workspace = true

mavuika-entity.workspace = true
mavuika-proto.workspace = true
mavuika-message.workspace = true
