[package]
name = "sakura-environment"
edition = "2021"
version.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
tracing.workspace = true

sakura-entity.workspace = true
sakura-proto.workspace = true
sakura-message.workspace = true
